const BASE64_IMAGES = {
  WINE_BASE64:
    "data:image/png;base64," +
    "iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPCAYAAAA71pVKAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAB2SURBVHgBtZI5DgAhCADB40X+/x++wMTE2kqWPRsLMZDsNBY4XAHgJ/B7HVjIOR9SXMzKzGiVkYjAImMpha7KUGslrcy996fl1prTyhBCeD+49WTLCOK7qxgjqOV73h1L2Xs/daCSxxhTElNlSRZJKcXdlZk5AXu6JHknsO8lAAAAAElFTkSuQmCC",
};

export default BASE64_IMAGES;
