import type { Metadata } from "next";
import { sfPro } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Wine App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sfPro.variable}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
