import type { Metadata } from "next";
import { sfPro } from "./fonts";
import "./globals.css";
import { Gnb } from "@/components";
import QueryProvider from "@/providers/query-provider";
import Card from "@/components/card/card";

export const metadata: Metadata = {
  title: "Wine App",
  description: "Generated by create next app",
};
const DUMMY_DATA = [
  {
    id: 475,
    name: "Veuve Clicquot Yellow Label 2016",
    region: "Champagne, France",
    image:
      "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Wine/user/364/1732326550631/image30.png",
    price: 99000,
    type: "SPARKLING",
    avgRating: 4.33,
    reviewCount: 3,
    recentReview: {
      id: 1241,
      content:
        "한동안 위시였던 뵈브 클리코 옐로우라벨! 새그러운 맛이 입안을 가득 채우고 꽃향기가 풍부하니 과연 좋은 와인이었습니다. 가격이 유일한 흠ㅠㅠ",
      createdAt: "2024-12-01T16:03:01.326Z",
      updatedAt: "2024-12-01T16:03:01.326Z",
    },
    userId: 364,
  },
  {
    id: 461,
    name: "Force Majeure Cabernet Sauvignon 2011",
    region: "Washington, USA",
    image:
      "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Wine/user/364/1732326589740/image9.png",
    price: 68000,
    type: "RED",
    avgRating: 5,
    reviewCount: 1,
    recentReview: {
      id: 1215,
      content:
        "과일 향과 부드러운 탄닌이 조화를 이루는 와인으로, 초보자도 부담 없이 즐길 수 있습니다.",
      createdAt: "2024-11-29T17:06:30.248Z",
      updatedAt: "2024-11-29T17:06:30.248Z",
    },
    userId: 376,
  },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={sfPro.variable}>
      <body className="mt-32">
        <QueryProvider>
          <Gnb />
          <div className="grid max-w-[800px] grid-cols-1 gap-x-[64px] gap-y-[60px] tablet:grid-cols-2 pc:grid-cols-2">
            <Card
              image={DUMMY_DATA[0].image}
              reviewCount={DUMMY_DATA[0].reviewCount}
              name={DUMMY_DATA[0].name}
              region={DUMMY_DATA[0].region}
              price={DUMMY_DATA[0].price}
            />
            <Card
              image={DUMMY_DATA[1].image}
              avgRating={DUMMY_DATA[1].avgRating}
              reviewCount={DUMMY_DATA[1].reviewCount}
              name={DUMMY_DATA[1].name}
              recentReview={DUMMY_DATA[1].recentReview}
            />
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
