import type { Metadata } from "next";
import { sfPro } from "./fonts";
import "./globals.css";
import { Gnb, FloatingActions } from "@/components";
import QueryProvider from "@/providers/query-provider";
import getMe from "@/api/user/get-me";
import KaKaoInitializer from "@/lib/kakao-initializer";
import ToastProvider from "@/providers/toast/toast-provider";

export const metadata: Metadata = {
  title: "Wine App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const userInfo = await getMe();

  return (
    <html lang="ko" className={sfPro.variable}>
      <body className="scrollbar-hide">
        <QueryProvider>
          <Gnb user={userInfo} />
          {children}
          {modal}
          <FloatingActions />
          <ToastProvider />
        </QueryProvider>
        <KaKaoInitializer />
      </body>
    </html>
  );
}
