# Workflow name
name: "Chromatic Deployment"

# Event for the workflow
on:
  push:
    branches:
      - develop # develop 브랜치에 푸시될 때
  pull_request:
    types: [opened, synchronize, labeled, unlabeled] # PR 이벤트 종류

# List of jobs
jobs:
  chromatic:
    name: "Run Chromatic"
    runs-on: ubuntu-latest

    # develop 브랜치이거나 chromatic 라벨이 있을 때만 실행
    if: |
      github.ref == 'refs/heads/develop' || 
      contains(github.event.pull_request.labels.*.name, 'chromatic')

    # Job steps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: yarn

      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
